import {Card} from './card-info';

export const CARDSTACK: Card[] = [
    { id: 0, picture:"assets/images/molecules.jpg", title: "Creating Sleek Data Presentations", description: "The presentation of data can impress a client if it is shown in a logical and creative way. This application will allow for heat maps and chart generators to show clients.", contact: "Johnathon.Doe@cgi.com", tags: ["Data Presentation"]},
    { id: 1, picture:"assets/images/buildings.jpg", title: "CGI Background and Stock Image Site", description: "CGI members should have a single site for CGI backgrounds for Teams meetings and CGI stock photos for presenting information. ", contact: "Tim.Doe@cgi.com", tags: ["Teams Background"]},
    { id: 2, picture:"assets/images/blocks.jpg", title: "Destress Application", description: "Working from home can become exhausting and unhealthy for our well-being. An application that reminds you to step outside or walk around.", contact: "jimmy.smith@cgi.com", tags: ["Mental Health"]},
    { id: 3, picture:"assets/images/buttons.jpg", title: "Virtual Whiteboard ", description: "Whiteboarding new ideas always gets a problem off the ground. A way to use a virtual whiteboard would help in this process. ", contact: "timmy.smith@cgi.com", tags: ["Project Planning"]},
    { id: 4, picture:"assets/images/phone.jpg", title: "Therapy Dogs in Office", description: "Therapy Dogs would be amazing. Everyone likes dogs and can destress.", contact: "tommy.doe@cgi.com", tags: ["Dogs"]},
    { id: 5, picture:"assets/images/tags.jpg", title: "Therapy Cats in Office", description: "Cats also provide comfort to members who may be stressed from a long day of working.", contact: "george.doe@cgi.com", tags: ["Cats"]},
    { id: 6, picture:"assets/images/handshake.jpg", title: "Collaboration between BU's", description: "An application that would allow for members across different Business Units within CGI to collaborate on ideas.", contact: "Dennis.Russell@cgi.com", tags: ["CGIdea"]},
    { id: 7, picture:"assets/images/twopeople.jpg", title: "CGI Contact Manager", description: "A simple way to keep track of everyone you are in contact with in CGI. Keepig track of Outlook and Teams contacts can become confusing", contact: "Jim.Doe", tags: ["Contact Storage"]},
    { id: 8, picture:"assets/images/man-desk-laptop-charts.jpg", title: "More Phishing Trainings!", description: "CGI needs more phishing security trainings. The clicking of a malicous link could cost the company millions if data falls in the wrong hands.", contact: "Johnny.Doe@cgi.com", tags: ["Phishing Security"]},
    { id: 9, picture:"assets/images/mobile-transactions.jpg", title: "Project Planning App", description: "The planning phase is essential to the success of any project worked on at CGI. A list for tasks to be completed, tasks being worked on, and completed tasks helps with project progression.", contact: "Jane.Doe@cgi.com", tags: ["Project Planning"]},
];