import {Card} from './card-info';

export const CARDSTACK: Card[] = [
    { id: 0, picture:"assets/images/kitty1.jpg", title: "My great idea", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis hendrerit dolor magna eget est.", contact: "contactme@cgi.com", tags: "IoT      Retail      Security"},
    { id: 1, picture:"assets/images/kitty2.jpg", title: "Another idea", description: " Nam at lectus urna duis. Eu augue ut lectus arcu bibendum at varius. In nisl nisi scelerisque eu ultrices vitae. ", contact: "contactme@cgi.com", tags: "IoT      Retail      Security"},
    { id: 2, picture:"assets/images/kitty3.jpg", title: "Keep them coming", description: "Facilisi nullam vehicula ipsum a arcu cursus. Convallis a cras semper auctor.", contact: "contactme@cgi.com", tags: "IoT      Retail      Security"},
    { id: 3, picture:"assets/images/kitty4.jpg", title: "More ideas please!", description: "Gravida rutrum quisque non tellus orci ac. Id venenatis a condimentum vitae sapien. Sed vulputate odio ut enim blandit. ", contact: "contactme@cgi.com", tags: "IoT      Retail      Security"},
    { id: 4, picture:"assets/images/kitty1.jpg", title: "So many ideas...", description: "In ornare quam viverra orci sagittis eu volutpat odio facilisis. Scelerisque eleifend donec pretium", contact: "contactme@cgi.com", tags: "IoT      Retail      Security"},
    { id: 5, picture:"assets/images/kitty2.jpg", title: "Idea overload", description: "Semper risus in hendrerit gravida rutrum quisque. Magna fermentum iaculis eu non diam phasellus.", contact: "contactme@cgi.com", tags: "IoT      Retail      Security"},
    { id: 6, picture:"", title: "Collaboration between BU's", description: "An application that would allow for members across different Business Units within CGI to collaborate on ideas.", contact: "Patrick.Burbank@cgi.com", tags: "CGIdea"},
    { id: 7, picture:"", title: "CGI Contact Manager", description: "A simple way to keep track of everyone you are in contact with in CGI. Keepig track of Outlook and Teams contacts can become confusing", contact: "Jim.Doe", tags: "Contact Storage"},
    { id: 8, picture:"", title: "More Phishing Trainings!", description: "CGI needs more phishing security trainings. The clicking of a malicous link could cost the company millions if data falls in the wrong hands.", contact: "Johnny.Doe@cgi.com", tags: "Phishing Security"},
    { id: 9, picture:"", title: "Project Planning App", description: "The planning phase is essential to the success of any project worked on at CGI. A list for tasks to be completed, tasks being worked on, and completed tasks helps with project progression.", contact: "Jane.Doe@cgi.com", tags: "Project Planning"}
];